#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cat /etc/hosts | grep -v 127.0.0.1 > temp
echo "127.0.0.2 localhost" >> temp
echo "8.8.8.8 facebook.com" >> temp

cat temp > /etc/hosts
rm temp